[versions]
android-sdk-min = "23"
android-sdk-target = "36"
android-sdk-compile = "36"
dagger = "2.57.2"
kotlin = "2.2.21"
lifecycle = "2.10.0"

[libraries]
activity-compose = "androidx.activity:activity-compose:1.12.0"
# note to self, Compose dependencies go as follows:
# runtime <- ui <- foundation-layout <- animation <- foundation <- material
compose-bom = "androidx.compose:compose-bom:2025.11.01"
compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
javapoet = "com.squareup:javapoet:1.13.0"
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
koin-compose = "io.insert-koin:koin-androidx-compose:4.1.1"

# test libraries
espresso-core = "androidx.test.espresso:espresso-core:3.7.0"
junit-jupiter = "org.junit.jupiter:junit-jupiter:6.0.1"
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:6.0.1"
test-runner = "androidx.test:runner:1.7.0"
truth = "com.google.truth:truth:1.4.5"

# plugin dependencies
android-gradle-plugin = "com.android.tools.build:gradle:8.13.1"
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.20"
kotlin-compose-compiler-plugin = "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.21"

[plugins]
anvil = { id = "com.squareup.anvil", version = "2.7.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
versions-config = { id = "dev.olshevski.versions", version = "1.0.5" }